# Generated by Django 3.0.8 on 2021-02-12 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='icomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.icomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.intern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
    ]
