# Generated by Django 3.0.8 on 2021-02-14 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210212_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='icomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.icomment')),
            ],
        ),
        migrations.CreateModel(
            name='interns',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('field', models.CharField(max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='intern',
            name='email',
        ),
        migrations.DeleteModel(
            name='icomments',
        ),
        migrations.DeleteModel(
            name='intern',
        ),
        migrations.AddField(
            model_name='icomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.interns'),
        ),
        migrations.AddField(
            model_name='icomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user'),
        ),
    ]
